### ISSUE TITLE
Array Inventory Update- Numbat

### ISSUE THREAD

**Issue by shannonrankin** [Kourtney-Burger/Inventree#13]
Click green 'Submit new issue' button below to activate issue check boxes. Select one of the check boxes then edit the issue by clicking the three dots at the top, select edit, and fill in the form following the directions for each question.   

If information regarding additional inventory items needs to be updated, please fill out the associated issue template. This includes hydrophones not already associated with an array, recorders, GPS units, depth sensors, computers, and other miscellaneous items.

# **I'm submitting a …**
- [ ] New Array  
- [x] Update to Current Array

### **Array Name**  

- SW-IL17n-H1H2H3 (numbat)

### **Array Condition**  
  
- Needs Repair

### **Array Current Location and Contact**

- PIFSC, Honolulu, HI

- Jennifer Keating
  
### **If 'Needs Repair' or 'Other' was chosen above under 'Condition', explain here:**  

- shark bite to tubing/leaks

## **For New Arrays Only**
<details><summary> Hydrophone Information </summary> 

  

#### **Channel 1 Hydrophone**
- **Model:** 
- **Serial #:** 
- **Distance (m):** 

#### **Channel 2 Hydrophone**
- **Model:** 
- **Serial #:** 
- **Distance (m):** 

#### **Channel 3 Hydrophone**
- **Model:** 
- **Serial #:** 
- **Distance (m):** 
</details>
  
## Any Additional Information
  
- Two changes: (1) location update (shipping from OSU to Hawaii) and (2) needs repair. Jennifer will repair array and use during HICEAS survey later this year.

**Comment by Kourtney-Burger** [comment]
@shannonrankin I see this is for the Numbat but what needs to be updated for it?

**Comment by shannonrankin** [comment]
Strange... not sure why the info did not save, will try again.

**Comment by shannonrankin** [comment]
@Kourtney-Burger Please confirm that this has updated on your end-- thanks! (It looks good on my end-- but it also did last time as well!)

**Comment by Kourtney-Burger** [comment]
looks good! I will update this in inventory, thanks!
