### ISSUE TITLE
Array Inventory Update

### ISSUE THREAD

**Issue by shannonrankin** [Kourtney-Burger/Inventree#14]
Click green 'Submit new issue' button below to activate issue check boxes. Select one of the check boxes then edit the issue by clicking the three dots at the top, select edit, and fill in the form following the directions for each question.   

If information regarding additional inventory items needs to be updated, please fill out the associated issue template. This includes hydrophones not already associated with an array, recorders, GPS units, depth sensors, computers, and other miscellaneous items.

# **I'm submitting a …**
- [ ] New Array  
- [ ] Update to Current Array

### **Array Name**  

- 

### **Array Condition**  
  
- 

### **Array Current Location and Contact**

- 

- 
  
### **If 'Needs Repair' or 'Other' was chosen above under 'Condition', explain here:**  

- 

## **For New Arrays Only**
<details><summary> Hydrophone Information </summary> 

  

#### **Channel 1 Hydrophone**
- **Model:** 
- **Serial #:** 
- **Distance (m):** 

#### **Channel 2 Hydrophone**
- **Model:** 
- **Serial #:** 
- **Distance (m):** 

#### **Channel 3 Hydrophone**
- **Model:** 
- **Serial #:** 
- **Distance (m):** 
</details>
  
## Any Additional Information
  
- Please modify LOCATION and STATUS (as both have changed). It is possible I already asked you to update this-- but better safe than sorry!

**Comment by Kourtney-Burger** [comment]
@shannonrankin what array is this for? I only see the comment to modify the location and status but not any other information regarding the array
