### ISSUE TITLE
Computer Inventory Update- SWC-SRANKIN2-D

### ISSUE THREAD

**Issue by shannonrankin** [Kourtney-Burger/Inventree#15]
Click green 'Submit new issue' button below to activate issue check boxes. Select one of the check boxes then edit the issue by clicking the three dots at the top, select edit, and fill in the form following the directions for each question.   

# **I'm submitting a …**
- [ ] New Computer 
- [x] Update to Current Computer

### **Computer Name**
-  SWC-SRANKIN2-D

### **Computer Make/Model**
-  Dell Optiplex 755

### **Computer Serial Number**
-  1X44LH1

### **Computer CD Number**
-  CD0001527298

### **Computer Name**
-  SRANKIN2

### **Computer Condition**

-  Other

### **If 'Needs Repair' or 'Other' was chosen above under 'Condition', explain here:**  

- Needs to be Surplused 

### **Computer Current Location and Contact**

- 

- 

## Any Additional Information
  
-

**Comment by Kourtney-Burger** [comment]
What is the process for surplussing a computer? Is there anything I need to do for this one and SWC-SRANKIN3-D (besides logging it in inventory)?

**Comment by shannonrankin** [comment]
Normally, yes there is a process. In this case, Laurie will go ahead & surplus them for us. Only need to change in inventory. Thanks!
