### ISSUE TITLE
Surplus- Computer Inventory Update

### ISSUE THREAD

**Issue by shannonrankin** [Kourtney-Burger/Inventree#17]
Click green 'Submit new issue' button below to activate issue check boxes. Select one of the check boxes then edit the issue by clicking the three dots at the top, select edit, and fill in the form following the directions for each question.   

# **I'm submitting a …**
- [ ] New Computer 
- [x] Update to Current Computer

### **Computer Name**
-  

### **Computer Make/Model**
-  

### **Computer Serial Number**
-  

### **Computer CD Number**
-  

### **Computer Name**
-  

### **Computer Condition**

-  

### **If 'Needs Repair' or 'Other' was chosen above under 'Condition', explain here:**  

- 

### **Computer Current Location and Contact**

- 

- 

## Any Additional Information
  
- Please see attached form-- I believe two of these I believe were surplussed, but the third is a 'new' one. Please let me know if you have any questions

**Comment by shannonrankin** [comment]
[Log 266_267_283 CD0001469086_CD0001527298_CD0004091683 Rankin.pdf](https://github.com/Kourtney-Burger/Inventree/files/10450058/Log.266_267_283.CD0001469086_CD0001527298_CD0004091683.Rankin.pdf)
Here is the form with the S/N of the computers that are being surplussed.

**Comment by Kourtney-Burger** [comment]
Thanks, I just linked this form to the surplus computers on the inventory spreadsheet
