### ISSUE TITLE
GPS Device Inventory Update

### ISSUE THREAD

**Issue by shannonrankin** [Kourtney-Burger/Inventree#18]
Click green 'Submit new issue' button below to activate issue check boxes. Select one of the check boxes then edit the issue by clicking the three dots at the top, select edit, and fill in the form following the directions for each question.   

If information regarding entire arrays needs to be updated, please fill out the associated issue template.

# **I'm submitting a …**
- [ ] New GPS Device  
- [x] Update to Current GPS Device

### **GPS Name**

- 0-3384777 to be renamed S0-777 

### **GPS ID**

- 

### **GPS Condition**
 
- 

### **GPS Current Location and Contact**

- 

- Anne Simonis

### **If 'Other' was chosen above under 'Condition', explain here:**  

- 
  
## Any Additional Information
  
- The contract for this device with Lonestar was initiated on Jan 16, 2023 for one year; this device was relabeled and will be shipped out to Anne Simonis in the near future. This makes me realize that we should have an entry for our GPS identifying their subscription date-- we need to keep track of this so we know when to re-up the subscriptions. Thanks!

**Comment by Kourtney-Burger** [comment]
This comment was on the old inventory spreadsheet for this device; July 2022 cancelled subscription & released from ; Rock7/Ground Control SolarOne. Has the subscription been reactivated?

**Comment by shannonrankin** [comment]
Yes, device was reactivated, but with Lonestar (not Rock7/Ground Control). In July 2022 I cancelled the subscription service with Rock7/GroundControl (my experience with them was very frustrating). We need this device for CCC survey, so I activated it with Lonestar. All of our other solar GPS (except for one that is an Iridium) are now on Lonestar. Thanks!

**Comment by Kourtney-Burger** [comment]
Ok! This has been updated in inventory
