### ISSUE TITLE
GPS Inventory Update:

### ISSUE THREAD

**Issue by shannonrankin** [Kourtney-Burger/Inventree#19]
### I'm submitting a ...

Update to a current GPS device

### GPS Name

ESN: 0-2574327 (AD)  ESN: 0-2574334 (AE)  ESN: 0-2571819 (AF)  ESN: 0-2573891 (AG)  ESN: 0-2574328 (AH)  ESN: 0-2572044 (FB)  ESN: 0-2404008 (Gen3A)  ESN: 0-2468190 (Gen3F)  ESN: 0-2571609 (T)  ESN: 0-2571709 (U)

### GPS Device Current Location and Contact

varied

### GPS Condition

Good

### Any Additional Information

All subscriptions for these devices are set to expire 1 day prior to their renewal date. See confirmation email to Shannon Rankin on 2/1/2023. 

### Contact Details

shannon.rankin@noaa.gov

**Comment by Kourtney-Burger** [comment]
Are you planning to cancel 0-2571609 (T) subscription? I had a note that this was not pinging correctly and to cancel it (renewal data 3/25/2023)

**Comment by shannonrankin** [comment]
This is one of the (many) units identified. Perhaps you cannot see the larger list? Let me know if not-- it is a total of ten SPOT devices

**Comment by Kourtney-Burger** [comment]
Oh sorry, that's my fault I skipped over that one. These have all been updated!

**Comment by Kourtney-Burger** [comment]
Will we need to have ESN: 0-2571819 (AF) (SFSU) and ESN: 0-2574328 (AH) (HSU) sent back to us? And then will they need to be replaced once the subscription expires? (both still good until 7/14)

**Comment by shannonrankin** [comment]
Ah- yes-- if its not too late, ask Eric Bjorkstedt to return all of his SPOT devices when he returns the other gear in the Pelican. He is no longer using them. 

Anne will give us her spot(s) in Morro Bay. Anne may want to use them on ACCESS.
